spring:
  application:
    name: user-serivce

  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username : root
    password : 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "user-service-pet-project-hs256-secret-key-32b"
  access-duration: 1800
  refresh-duration: 604800


